### ISSUE TITLE
Crystal not used?

### ISSUE THREAD

**Issue by wallarug** [adafruit/uf2-samdx1#38]
Hi!

Apologies if this is not the correct place to raise this.

I have a Feather M0 Basic Proto and noticed that all of the bootloaders / uf2 appear to not use the crystal on the board attached to PA00 and PA01 - regardless of which board.

Is there any reason why the X2 crystal is on the board and not used in the default bootloaders?  Why have the X2 crystal at all?

I am just curious and interested.

Thank you.

**Comment by dhalbert** [comment]
The bootloader clocks work well enough without using the crystal, especially since we can do clock recovery from the USB signals. Having just one way to do the clocks reduces the amount of code we need to maintain. Any application program loaded or started by the bootloader is free to reconfigure the clocks to use the crystal. Arduino programs and CircuitPython do use the crystal if available.
