### ISSUE TITLE
Builds for SAMD51G19A broken - unknown cause

### ISSUE THREAD

**Issue by wallarug** [adafruit/uf2-samdx1#67]
Afternoon,

I have been trying to build a bootloader for the SAMD51G19A but hit a small road block.

I forked the repository on Wednesday (last week).  My builds from that time have a version code of `v3.6.0.0-2-g4fdf0fe`.    They work perfectly fine on the board.

I then ran `git submodule update` about 2 hours ago and now all the builds I make do not work on the board.  They have version code `v3.6.0-4-g09c839b-dirty`.

I cannot find what changed after the sub-module update.  According to the operating system nothing changed except for the builds.  I can clearly see in the console history that this change happened after ran git submodule update.

According to the debugger, the bootloader is crashing on line 480 of src/cdc_enumerate.c.

The only reason I updated was because someone else was getting the dodgy g09 builds but I was not.

There are no obvious changes to any submodules or this repository (except for one on June 14).  Is anyone able to explain how the version code gets generated and then I might be able to back trace this issue.

Thank you

VirtualBox Ubuntu 16.04.5
Repository Fork: https://github.com/wallarug/uf2-samdx1
Build Command:  `make BOARD=robohatmm151`

**Comment by tannewt** [comment]
What does `git status` show? The -dirty originates from `git describe`.

**Comment by wallarug** [comment]
![image](https://user-images.githubusercontent.com/11770912/59737903-b6c17600-92a2-11e9-8722-94d1281a7790.png)

I don't think this is any help.  

FYI:  I included the build file.  This is not a mistake, just a temporary change.

**Comment by dhalbert** [comment]
Could you copy/paste th text instead of a screen shot? I have color-vision issues and can't read the text in the image above.

I cloned your repo, did `make clean`, and built an `itsybitsy_m4` bootloader, which should be similar to yours: it's SAMD51G19A. It loaded fine and is running.

What version of arm gcc are you using? We're using 7.3.1. There were no submodule repo changes that I know of.

Could you clone your repo fresh, roll back a few commits, to say, 4fdf0fe, and see if it's still bad? Then advance to e88dd3a, and then 09c839b (with all the `.o` checkins, etc.). Maybe you did this already?

**Comment by wallarug** [comment]
Hi @dhalbert  and @tannewt ,

I've done a bit of investigation and collaboration.  I think it is just the way the computer is configured.  I can build good builds but my colleague cannot.  Even on the same commit.

We will investigate further together.  Since we have a working build now.
